services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=farmtrade
      - POSTGRES_USER=farmtrade
      - POSTGRES_DB=farmtrade
    networks:
      - postgres

  backend:
    image: ghcr.io/farm-trade/farm-trade-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=farmtrade
      - DB_USER=farmtrade
      - DB_PASSWORD=farmtrade
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - PORT=8000
      - TWILIO_SID=AC2efae4bfa510c1ba458969bafdabba96
      - TWILIO_TOKEN=0ddacae69cbe4efafb15613b264b8404
      - TWILIO_NUMBER=+19108125369
    networks:
      - postgres

  frontend:
    image: ghcr.io/farm-trade/farm-trade-frontend-additional
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  postgres:
    driver: bridge