services:
  farm-trade-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=farmtrade
      - POSTGRES_USER=farmtrade
      - POSTGRES_DB=farmtrade
    networks:
      - postgres

  farm-trade-backend:
    image: ghcr.io/farm-trade/farm-trade-backend
    ports:
      - "8000:8080"
    depends_on:
      - farm-trade-db
    environment:
      - DB_NAME=farmtrade
      - DB_USER=farmtrade
      - DB_PASSWORD=farmtrade
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - TWILIO_SID=AC2efae4bfa510c1ba458969bafdabba96
      - TWILIO_TOKEN=a81853ab12b41fefa88db75c6db4d9a2
      - TWILIO_NUMBER=+19108125369
    networks:
      - postgres

networks:
  postgres:
    driver: bridge