spring:
  security:
    basic:
      enabled: false
    jwt:
      token:
        secret : ${JWT_SECRET:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9}
        expired : 3600000

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:

    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:farmtrade}
    username: ${DB_USER:farmtrade}
    password: ${DB_PASSWORD:farmtrade}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

server:
  port : ${PORT:8080}

twilio:
  accountSid: ${TWILIO_SID:AC2efae4bfa510c1ba458969bafdabba96}
  authToken: ${TWILIO_TOKEN:a81853ab12b41fefa88db75c6db4d9a2}
  number: ${TWILIO_NUMBER:+19108125369}

user:
  sendActivation: ${SEND_ACTIVATION:true}

orderRequest:
  complete:
    interval: 60000
    disable: ${ORDER_REQUEST_COMPLETING_DISABLE:false}

file:
  upload-dir: uploads/
  image-dir: img/
  image-types:
    - png
    - jpg
    - jpeg


