spring:
  security:
    basic:
      enabled: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:

    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:farmtrade}
    username: ${DB_USER:farmtrade}
    password: ${DB_PASSWORD:farmtrade}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

twilio:
  accountSid: ${TWILIO_SID:AC2efae4bfa510c1ba458969bafdabba96}
  authToken: ${TWILIO_TOKEN:a81853ab12b41fefa88db75c6db4d9a2}
  number: ${TWILIO_NUMBER:+19108125369}

user:
  sendActivation: ${SEND_ACTIVATION:true}