spring:
  security:
    basic:
      enabled: false
    jwt:
      token:
        secret : ${JWT_SECRET}
        expired : 3600000

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:

    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:farmtrade}
    username: ${DB_USER:farmtrade}
    password: ${DB_PASSWORD:farmtrade}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_TOKEN}
  number: ${TWILIO_NUMBER}