spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://${HOST:localhost}:${DB_PORT:5432}/postgres
    username: ${DB_USER:TEST}
    password: ${DB_PASSWORD:TEST}
    driverClassName: org.postgresql.Driver