spring:
  security:
    basic:
      enabled: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    username: ${DB_USER:TEST}
    password: ${DB_PASSWORD:TEST}
    driverClassName: org.postgresql.Driver