name: Pull Request Check

env:
  IMAGE_NAME: "farm-trade-backend"
  IMAGE_REGISTRY: "ghcr.io"
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }}
          registry: ${{ env.IMAGE_REGISTRY }}
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        run: echo ${{ github.repository}}

      - name: Image Report
        run: echo Image name is ${{ env.IMAGE_REGISTRY }}/farm-trade/${{ env.IMAGE_NAME }}:${{ github.sha }}
